#! /bin/bash
# chkconfig: - 10 90
# /etc/init.d/teamcity-server
#

USER=teamcity-server
TEAMCITY_DATA_PATH=/var/lib/teamcity-server
TEAMCITY_DIR=/opt/teamcity-server

# source teamcity-specific config
[ -e /etc/sysconfig/teamcity ] && . /etc/sysconfig/teamcity

start() {
  echo "starting teamcity-server"
  su -s /bin/bash -c "$TEAMCITY_DIR/bin/teamcity-server.sh start" $USER
}

stop() {
  echo "stopping teamcity-server"
  su -s /bin/bash -c "$TEAMCITY_DIR/bin/teamcity-server.sh stop" $USER
}
 
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    start
    RETVAL=$?
    ;;
  stop)
    stop
    RETVAL=$?
    ;;
  restart)
    start
    stop
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
 
exit $RETVAL
